### ISSUE TITLE
Installation hangs forever at 'building satisfactory-server-depot: Got AppInfo for 1690800'

### ISSUE THREAD

**Issue by zorrobert** [nekowinston/satisfactory-server-flake#2]
First of all, thank you so much for packaging this. I tried installing the flake on my system, but it hangs when running nixos-rebuild switch.

In my flake.nix:

```
{
  inputs = {
    satisfactory-server = {
      url = "github:nekowinston/satisfactory-server-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  }
  outputs = { self, nixpkgs, satisfactory-server, ... }@inputs:
  {
    nixosConfigurations = {
      Desktop-NixOS = nixpkgs.lib.nixosSystem {
        specialArgs = { inherit inputs; };
        system = "x86_64-linux";
        modules = [
          ./configuration.nix
          ./satisfactory-server.nix
          inputs.satisfactory-server.nixosModules.satisfactory
        ]);
      };
    }
  }
}
```

In my satisfactory-server.nix:
```
{ config, lib, pkgs, inputs, ... }:
{
  services.satisfactory = {
    enable = true;
  };
}
```

When I run `sudo nixos-rebuild switch` the rebuild is normal until it tries to build the satisfactory-server-depot, where it just hangs forever with the message '[1/0/11] building satisfactory-server-depot: Got AppInfo for 1690800'.

I also tried this:
```
{ config, lib, pkgs, inputs, ... }:
{
  environment.systemPackages = [
    pkgs.satisfactory-server
  ];
}
```

There I got:
       error: attribute 'satisfactory-server' missing

       at /nix/store/lj890s87hczxgm3qpvwg7r2zhim7pabm-source/satisfactory-server.nix:8:5:

            7|   environment.systemPackages = [
            8|     pkgs.satisfactory-server
             |     ^
            9|   ];

Can you show me the correct way to import the flake?

**Comment by nekowinston** [comment]
Hey there,
if it's getting to that point, I bet the current `src` is just out of date; I'll update it in a bit.
If you want to use the bare `pkgs.satisfactory-server`, you need to also apply the overlay of the flake inside your nixpkgs import: 
`import nixpkgs { overlays = [inputs.satisfactory-server.overlays.default]; };`

The module will do that for itself tho:
https://github.com/nekowinston/satisfactory-server-flake/blob/cf910484a0faad134559a5ed0006099c7f85b997/modules/satisfactory.nix#L84-L88

**Comment by nekowinston** [comment]
Should work now, seems the `flake.lock` also needed to be bumped.

**Comment by zorrobert** [comment]
Thanks for the quick reply! I installed the server now like you wrote in the readme, but sadly still have the same issue where nixos-rebuild hangs at "building satisfactory-server-depot: Got AppInfo for 1690800".

**Comment by nekowinston** [comment]
Can you try without overriding the nixpkgs input via `nixpkgs.follows = "nixpkgs"`?
Or building it from github directly via:
```command
NIXPKGS_ALLOW_UNFREE=1 nix build --impure github:nekowinston/satisfactory-server-flake#packages.x86_64-linux.default
```

Before I bumped the flake lock, it also got stuck on the `Got AppInfo` step, but I don't really know why that happens.

**Comment by zorrobert** [comment]
I just tried removing the `nixpkgs.follows` but that didn't fix it, but building from github worked. I'm still on 24.05, could that be an issue?

**Comment by zorrobert** [comment]
I just tried rebuilding again after running the `nix build` command and `nixos-rebuild` now completes without issues. I just checked and the server works like it should. 
Thank you so much for taking the time to help me out, I really appreciate it :)
